language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - cmake
      
before_script:
  - mkdir $TRAVIS_BUILD_DIR/BUILD

script:
  - cd $TRAVIS_BUILD_DIR/BUILD
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$CXX
  - make
