language: cpp
dist: trusty
sudo: false

services:
  - docker

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - cmake

script:
  - docker build -t eventtimings .
    
